import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import {MainNavBar} from "@components";
import "@css/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="w-full sticky top-0 inset-x-0 pb-2">
          <div className="w-full h-20 bg-black/20 xl:px-[calc((100vw-1280px)/2)] backdrop-blur-lg">
            <MainNavBar/>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
